services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: "https://YOUR-BACKEND-URL.onrender.com"  # Replace after backend deploy

  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
