name: Markdown Link Check

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # Weekly Monday 03:00 UTC

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install markdown-link-check
        run: npm i -g markdown-link-check@3
      - name: Run link check
        run: |
          find . -name "*.md" -not -path "./node_modules/*" -print0 | xargs -0 -n1 markdown-link-check -q -c .mlc.config.json || true
